### ISSUE TITLE
Server down.

### ISSUE THREAD

**Issue by githubtefo** [Evgeny-/Firefox-OS-Weather#12]
Hi!
Since a couple of months the weather app is down.
Is there any way to fix it?
Thanks!

**Comment by Evgeny-** [comment]
HI, @githubtefo i've send letter to the worldweatheronline.

They are discontinued support for free api, https://discuss.worldweatheronline.com/t/free-api-has-now-been-discontinued/54 Premium api little bit pricey https://developer.worldweatheronline.com/api/pricing.aspx

May be I will do new build, with other api, but the marketplace is dead.

**Comment by githubtefo** [comment]
Yes, indeed. The whole FxOS is dead already, but I'm still using it.
The app is really nice and clean, may be you can try to rebuild it thinking also as a webapp.
Thank you Evgeny for your answer!
