### ISSUE TITLE
City Specificity

### ISSUE THREAD

**Issue by Poorchop** [Evgeny-/Firefox-OS-Weather#4]
Is it possible to show more information about cities when manually searching for and selecting one in order to ensure that we are selecting the correct city?

If one were to search "Arlington" for example, there would be no way to differentiate between Arlington in Texas, Virginia, Massachusetts, Washington, Tennessee, New York, and so forth.  It would help if specific states were listed alongside the cities so that the user doesn't end up picking a city with the same name but that happens to be across the country.

**Comment by Evgeny-** [comment]
Hope not too late :)

Fixed

**Comment by Poorchop** [comment]
Cool, thank you.
